[workspace.package]
version = "0.0.1"
authors = ["Mateusz Kondej <m@kondej.net>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/mateuszkj/ssh-test-server"

[workspace]
members = [
  "ssh-test-server",
  "ssh-test-server-cli"
]

