[workspace.package]
version = "0.1.2"
authors = ["Mateusz Kondej <m@kondej.net>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/mateuszkj/ssh-test-server"

[workspace]
resolver = "2"
members = ["ssh-test-server", "ssh-test-server-cli"]

