[package]
name = "ssh-test-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Running isolated ssh servers in integration tests"
documentation = "https://docs.rs/ssh-test-server"
repository.workspace = true
keywords = ["ssh", "test"]
categories = ["development-tools::testing"]


[dependencies]
anyhow = "1.0.70"
russh = "0.37.1"
russh-keys = "0.37.1"
futures = "0.3.28"
tokio = "1.27.0"
tracing = "0.1.37"
cmdline_words_parser = "0.2.1"
async-trait = "0.1.68"
portpicker = "0.1"
rand = "0.8"


[dev-dependencies]
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }
tracing-test = "0.2.4"
t-ssh-client = "0.2.1"
ssh2 = "0.9.4"
#cucumber = "0.19.1"
cucumber = { git = "https://github.com/cucumber-rs/cucumber.git", features = ["tracing"]}
timeout-readwrite = "0.3.3"



[[test]]
name = "ssh"
harness = false  # allows Cucumber to print output instead of libtest

