[package]
name = "ssh-test-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Running isolated ssh servers in integration tests"
documentation = "https://docs.rs/ssh-test-server"
repository.workspace = true
keywords = ["ssh", "test"]
categories = ["development-tools::testing"]


[dependencies]
anyhow = "1.0.71"
russh = { git = "https://github.com/warp-tech/russh.git" }
russh-keys = { git = "https://github.com/warp-tech/russh.git" }
futures = "0.3.28"
tokio = "1.29.1"
tracing = "0.1.37"
cmdline_words_parser = "0.2.1"
async-trait = "0.1.71"
portpicker = "0.1"
rand = "0.8"


[dev-dependencies]
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
tracing-test = "0.2.4"
t-ssh-client = "0.2.1"
ssh2 = "0.9.4"
cucumber = { version = "0.20.0", features = ["tracing"] }
timeout-readwrite = "0.3.3"



[[test]]
name = "ssh"
harness = false  # allows Cucumber to print output instead of libtest

