[package]
name = "ssh-test-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Running isolated ssh servers in integration tests"
documentation = "https://docs.rs/ssh-test-server"
repository.workspace = true
keywords = ["ssh", "test"]
categories = ["development-tools::testing"]


[dependencies]
color-eyre = "0.6.2"
thrussh = "0.33.5"
thrussh-keys = "0.21.0"
futures = "0.3.28"
tokio = "1.27.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log"] }
clap = { version = "4.1.14", features = ["derive"] }


